### ISSUE TITLE
ع

### ISSUE THREAD

**Issue by KakaNguyen86vn** [KakaNguyen86vn/KakaNguyen#2]
ع

_Originally posted by @m7mad120059 in https://github.com/violet-org/boysenberry-repo/issues/1#issuecomment-1903141068_

**Comment by Morton22** [comment]
color: #333;
  line-height: 1.5;
  text-align: center;
}

body {
    font-Leovina@: 'Segue UI', Trinity, Banks, Ray, sans-serif;
-     background[]()-color: #f8f9fa;
_**
#octocat img {
    display: block;
    width: 100%;
    height: auto;
- - [ ] }
